#!/usr/bin/env sh
set -eu

root=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

run_bazel() {
    directory=$1
    shift
    (cd "$root/$directory" && bazel "$@")
}

run_script() {
    directory=$1
    script=$2
    (cd "$root/$directory" && "./$script")
}

run_bazel smoke test --lockfile_mode=error //...
run_bazel failure_propagation test --lockfile_mode=error //...
run_bazel provider_transitive build --lockfile_mode=error //...
run_bazel collection build --lockfile_mode=error //...
run_script dependency_http check.sh
run_script dependency_http check_private_failures.sh
run_script dependency_git check.sh
run_script dependency_git check_private_failures.sh
run_bazel two_dependencies test --distdir=../dependency_http/testdata --distdir=testdata --lockfile_mode=error //...
run_bazel two_dependencies fetch --distdir=../dependency_http/testdata --distdir=testdata --lockfile_mode=error //...
run_bazel two_dependencies test --distdir=../dependency_http/testdata --distdir=testdata --lockfile_mode=error --nofetch //...
run_bazel monorepo test --lockfile_mode=error //...
run_bazel monorepo fetch --lockfile_mode=error //...
run_bazel monorepo test --lockfile_mode=error --nofetch //...
run_script multimodule check.sh
