module(
    name = "rules_odin_singlebuildfile_example",
    version = "0.0.0",
)

bazel_dep(name = "rules_odin", version = "0.2.0")
git_override(
    module_name = "rules_odin",
    commit = "1133b5efbe4472a8577567bc309c8c82f3ee2564",
    remote = "https://github.com/hguerra/rules_odin.git",
)

odin = use_extension("@rules_odin//odin:extensions.bzl", "odin")
odin.toolchain(odin_version = "dev-2026-06")
use_repo(odin, "odin_toolchains")

odin_deps = use_extension("@rules_odin//odin:deps_extensions.bzl", "odin_deps")
odin_deps.github(
    name = "toml_parser",
    commit = "10aee3739d1a144efe79e95d8a094e9c1563bb03",
    repository = "Up05/toml_parser",
)
odin_deps.github(
    name = "simpleenv",
    commit = "13d2b5c8c2fffb3a2eacaa42f3dc154dab7c4dc1",
    repository = "bymehul/simpleenv",
    source_subdir = "simpleenv",
)
use_repo(odin_deps, "simpleenv", "toml_parser")

register_toolchains("@odin_toolchains//:all")
